// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALp1_evaxO7oT4rty8cIwZtq6dMyCtBbw',
    appId: '1:87708129049:web:139518f2ee0e896d5c5788',
    messagingSenderId: '87708129049',
    projectId: 'takaliapp',
    authDomain: 'takaliapp.firebaseapp.com',
    storageBucket: 'takaliapp.firebasestorage.app',
    measurementId: 'G-FBB4XSWM9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bIurj023NuSdMq8sx749n9p07U3_mLw',
    appId: '1:87708129049:android:267651ccda11a6ef5c5788',
    messagingSenderId: '87708129049',
    projectId: 'takaliapp',
    storageBucket: 'takaliapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIy4bduadwVA2hpuKcRmTBtltcDnoEDj4',
    appId: '1:87708129049:ios:92af4be3475624ce5c5788',
    messagingSenderId: '87708129049',
    projectId: 'takaliapp',
    storageBucket: 'takaliapp.firebasestorage.app',
    iosBundleId: 'com.example.takali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIy4bduadwVA2hpuKcRmTBtltcDnoEDj4',
    appId: '1:87708129049:ios:92af4be3475624ce5c5788',
    messagingSenderId: '87708129049',
    projectId: 'takaliapp',
    storageBucket: 'takaliapp.firebasestorage.app',
    iosBundleId: 'com.example.takali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALp1_evaxO7oT4rty8cIwZtq6dMyCtBbw',
    appId: '1:87708129049:web:d3f10418f4ac917e5c5788',
    messagingSenderId: '87708129049',
    projectId: 'takaliapp',
    authDomain: 'takaliapp.firebaseapp.com',
    storageBucket: 'takaliapp.firebasestorage.app',
    measurementId: 'G-6N989TDSE5',
  );

}